Repository mesh-adaptation/animate, pull requests merged in 2024-09, with the labels that each got.

#142 Truncate infinite degree when passing to PETSc
  .github/workflows/test_suite.yml
  animate/metric.py
  test/test_adapt.py
Labels: bug, PRIORITY

#147 Expand workflows: citation check and changed-files
  .github/workflows/citation_check.yml
  .github/workflows/test_suite.yml
Labels: testing

#148 Reusable workflows
  .github/workflows/citation_check.yml
  .github/workflows/test_suite.yml
  Makefile
Labels: testing

#145 Bubble shear on the fly adapt demo
  demos/bubble_shear.py
  demos/demo_references.bib
  test/test_demos.py
Labels: documentation
