Repository mesh-adaptation/animate, pull requests merged in 2024-05, with the labels that each got.

#118 Account for updated `create_section`
  animate/metric.py
Labels: bug, PRIORITY

#116 Fixes for adapting in serial PR
  animate/adapt.py
  animate/checkpointing.py
  animate/metric.py
  animate/utility.py
  test/test_checkpoint.py
  test/test_utility.py
Labels: enhancement

#104 Defer to the wiki for installation instructions
  .github/workflows/docker.yml
  README.md
  docker/Dockerfile.firedrake
  docker/Makefile
  install/install_firedrake.sh
  install/install_firedrake_custom_mpi.sh
  install/petsc_options.txt
Labels: documentation, clarity, install

#119 #81 add import interpolate from __future__ and update function calls
  animate/metric.py
  animate/quality.py
  animate/recovery.py
Labels: bug

#120 Fix B linting rules
  animate/math.py
  animate/metric.py
  animate/utility.py
  pyproject.toml
  test/test_adapt.py
  test/test_setup.py
  test/test_utility.py
Labels: bug, clarity

#115 Enable mass lumping for projection operator
  animate/interpolation.py
  animate/utility.py
  demos/combining_metrics.py
  demos/ping_pong.py
  demos/simple_metric.py
  test/test_interpolation.py
  test/test_utility.py
Labels: enhancement

#125 Fixes for ping pong demo
  animate/interpolation.py
  animate/quality.py
  demos/combining_metrics.py
  demos/demo_references.bib
  demos/ping_pong.py
Labels: bug, documentation

#128 Add `CITATION.cff`
  .github/workflows/test_suite.yml
  CITATION.cff
  Makefile
  animate/adapt.py
  animate/math.py
  animate/metric.py
  animate/recovery.py
  demos/ping_pong.py
  pyproject.toml
  test/test_metric.py
  test/test_recovery.py
Labels: documentation

#134 Modify and run demos directly during testing
  demos/ping_pong.py
  test/test_demos.py
Labels: testing, clarity

#137 Temporarily skip hanging test
  test/test_adapt.py
Labels: bug
