Repository mesh-adaptation/animate, pull requests merged in 2024-12, with the labels that each got.

#163 Update mesh path in test
  test/test_adapt.py
Labels: bug, testing

#165 Fix path to docs repo
  .github/workflows/test_suite.yml
Labels: bug, testing, PRIORITY

#166 Simplify test workflow file
  .github/workflows/test_suite.yml
Labels: testing, clarity

#170 Introduce optional dev dependencies
  Makefile
  pyproject.toml
Labels: install
