Repository mesh-adaptation/animate, pull requests merged in 2024-03, with the labels that each got.

#83 Install Thetis in Dockerfile
  docker/Dockerfile.firedrake
Labels: install

#91 Temporary docker base image revert
  docker/Dockerfile.firedrake
  install/install_firedrake.sh
  install/install_firedrake_custom_mpi.sh
Labels: install

#90 Allow metric_parameters kwarg to RiemannianMetric
  animate/metric.py
  test/test_metric.py
Labels: refactor

#99 Introduce metric parameters documentation
  animate/metric.py
  test/test_adapt.py
  test/test_metric.py
Labels: documentation
