Repository mesh-adaptation/animate, pull requests merged in 2024-01, with the labels that each got.

#63 Add demos to testing
  test/test_demos.py
Labels: testing

#64 Bug-fix for Riemann init from tensor field (copy) with active tape
  animate/metric.py
Labels: bug

#62 Demo on combining metrics.
  demos/Makefile
  demos/combining_ellipse_intersection.svg
  demos/combining_metrics.py
Labels: documentation

#70 Add pre-commit hooks
  .gitignore
  .pre-commit-config.yaml
  Makefile
  demos/simple_metric.py
  pyproject.toml
  requirements.txt
Labels: enhancement

#68 Use `splitext` for demo test names
  test/test_demos.py
Labels: testing, refactor
